[program:unit3d-queue]
process_name=%(program_name)s_%(process_num)02d
command=php {{install_dir}}/artisan queue:work redis --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user={{web_user}}
numprocs=4
redirect_stderr=true
stdout_logfile={{install_dir}}/storage/logs/queue.log
stopwaitsecs=3600

[program:unit3d-echo]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/node /usr/bin/laravel-echo-server start --dir={{install_dir}}
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user={{web_user}}
numprocs=1
redirect_stderr=true
stdout_logfile={{install_dir}}/storage/logs/echo.log